comeet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('commit.urls')),
]

commit/urls.py
from django.urls import path
from . import views

app_name = 'commit'

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:id>', views.detail_commit, name='detail_commit'),
    path('detail/comment/<int:id>', views.detail_write_comment,
         name='detail_writer_comment'),
    path('detail/comment/delete/<int:id>',
         views.detail_delete_comment, name='detail_delete-comment'),
    path('write/', views.write_view, name='write_view'),
    path('edit/<int:id>', views.edit_view, name='edit_view'),
    path('write/delete/<int:id>', views.delete_view, name='delete_view'),
    path('detail/like/<int:id>', views.likes, name='like')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('log_in/', views.log_in_view, name='log_in'),
    path('log_out/', views.log_out_view, name='log_out'),
    path('sign_up/', views.sign_up_view, name='sign_up'),
    path('my_page/<int:id>', views.my_page_view, name='my_page'),
    path('user_page/<int:id>', views.user_my_view, name='user_page'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>
    <title>
      {% block title %}{% endblock %}
    </title>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css.css"/>

  </head>

  <body>
    <div class="board_wrap">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'commit:home' %}">
            <span class="co_base">
              Co.</span><span class="meet_base">Meet</span></a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent"></div>
          {% if user.is_authenticated %}
            <img src="https://i.ibb.co/pRGMQPW/image.png" alt=""/>
            <div class="dropdown">
              <a class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="dropdown_toggle"></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>{{ user.username }}</li>
                <li>
                  <a href="{% url 'user:log_out' %}" class="logout">로그아웃</a>
                </li>
                <li>
                  <a href="/my_page/{{ user.id }}">내 프로필</a>
                </li>
              </ul>
            </div>
          {% else %}
            <div class="sign_box">
              <a href="{% url 'user:log_in' %}" class="base_login">
                LOG IN</a>
              <span>|</span>
              <a href="{% url 'user:sign_up' %}" class="base_join">
                JOIN</a>
            </div>
          {% endif %}
        </div>
      </nav>
      {% block content %}{% endblock %}
      <footer class="footer">
        <p class="teamName">
          <span class="sco">Co.</span>
          <span class="smeet">
            Meet</span>
        </p>
        <p class="copyright">
          Copyright(c)2023 Team. rAinbow All rights reserved.
        </p>
      </footer>
    </div>
    {% verbatim %}
      <script src="/static/test.js"></script>
    {% endverbatim %}
  </body>

</html>

templates/main.html
{% extends 'base.html' %}
{% block title %}
  Co.Meet
{% endblock %}
{% block content %}
  <h2 class="title-center">메인 페이지</h2>
</br>
</br>
<div class="board_list_wrap">
<div class="board_list">
  <div class="top">
    <div class="num">카테고리</div>
    <div class="title">제목</div>
    <div class="writer">글쓴이</div>
    <div class="date">작성일</div>
    <div class="count">좋아요</div>
  </div>
  {% for cmt in commit %}
    <div>
      <div class="num">{{ cmt.category }}</div>
      <div class="title" style="text-align: center;">
        <a href="/detail/{{cmt.id}}">{{ cmt.title }}</a>
      </div>
      <div class="writer">{{ cmt.writer.username }}</div>
      <div class="date">{{ cmt.updated_at | date:"Y-m-d" }}</div>
      <div class="count">{{ cmt.like_commit }}</div>
    </div>
  {% endfor %}
</div>
{% if user.is_authenticated %}
  <div class="bt_wrap">
    <a href="{% url 'commit:write_view' %}" class="on">글쓰기</a>
  </div>
{% endif %}
</div>
{% endblock %}